# Generated by Django 5.2.9 on 2025-12-15 06:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='user_image',
            field=models.ImageField(default='user_profile.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
    ]
