# Generated by Django 5.2.9 on 2025-12-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_buyer_user_image_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='user_image',
            field=models.ImageField(default='profile/user_profile.jpg', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_image',
            field=models.ImageField(default='sellers/seller_profile.jpg', upload_to='sellers/'),
        ),
    ]
