# Generated by Django 5.2.9 on 2025-12-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_buyer_user_image_alter_seller_seller_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller')], default='seller', max_length=20),
        ),
    ]
