# Generated by Django 5.2.9 on 2026-01-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_buyer_role_seller_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
