# Generated by Django 5.2.9 on 2026-02-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_seller_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='user_image',
            field=models.ImageField(default='profiles/user_profile.jpg', upload_to='profiles/'),
        ),
    ]
